### PR TITLE
Update to Colmap 3.9.1 and added Dockerfile.

### PR DESCRIPTION
**Pull request by pablospe**
This PR updates the changes made to Colmap 3.9 and adds a Dockerfile. Usage:
```
export COLMAP_VERSION=3.9.1
export CUDA_ARCHITECTURES=70
docker build -t pyceres \
    --build-arg COLMAP_VERSION=${COLMAP_VERSION}  \
    --build-arg CUDA_ARCHITECTURES=${CUDA_ARCHITECTURES}  \
    -f Dockerfile .
```

A possible improvement for a future pull request is to create a runtime docker stage that only installs the essential dependencies and uses the compiled ceres-solver and colmap from the builder stage (this will reduce the docker image size considerably).

### CODE REVIEW

**Comment by pablospe** [comment]
@Phil26AT @sarlinpe I was wondering if you could take a look to this PR.

**Comment by sarlinpe** [comment]
LGTM. I don't use Docker so I don't really understand all these details.

**Comment by sarlinpe** [comment]
@pablospe Since COLMAP 3.9.1 the quaternions follow the Eigen format (xyzw instead of wxyz) but this wasn't updated here - so the user need to manually handle any conversion.

**Comment by pablospe** [comment]
Yes, you are right, this is not handle it here. Should we revert these changes?

**Comment by sarlinpe** [comment]
I'd rather revert for now and do a proper upgrade in https://github.com/cvg/pyceres/pull/27 - can you submit one and keep the Docker stuff if you need it?

**Comment by pablospe** [comment]
One question, it only uses only the camera models from Colmap, right? I was wondering if it would make sense to simply take a copy the `models.h` to avoid Colmap dependency in this repo? It is like a circular dependency, for compiling Colmap you need ceres, and for pyceres you need Colmap :)

**Comment by sarlinpe** [comment]
My plan is to move the bundle & PGO cost functions to pycolmap, such that pyceres handles only the core features without any dependency on COLMAP. But this requires some updates upstream to add covariances.

**Comment by pablospe** [comment]
Related PR (for the Dockerfile part): https://github.com/cvg/pyceres/pull/31

**Pull request merged**
